<?php if ($this->themeSetting('use_show_selector')): ?>

    <?php // If the local BC customizations are turned on in the theme settings, use them. ?>
    <?= $this->DHSelectShowPage($item) ?>

<?php else: ?>

    <?php // Otherwise, show the normal show page ?>
    <?php
    $escape = $this->plugin('escapeHtml');
    $this->htmlElement('body')->appendAttribute('class', 'item resource show');
    $this->headLink()->appendStylesheet($this->assetUrl('css/lightslider.min.css'));
    $this->headLink()->appendStylesheet($this->assetUrl('css/lightgallery.min.css'));
    $this->headScript()->appendFile($this->assetUrl('js/lightslider.min.js'));
    $this->headScript()->appendFile($this->assetUrl('js/lightgallery.min.js'));
    $this->headScript()->appendFile($this->assetUrl('js/lg-video.min.js'));
    $this->headScript()->appendFile($this->assetUrl('js/lg-zoom.js'));

    $lightMedia = [];
    $otherMedia = [];
    $whitelist = ['image/bmp', 'image/gif', 'image/jpeg', 'image/png', 'image/svg+xml'];
    foreach ($item->media() as $media) {
        $mediaType = $media->mediaType();
        $mediaRenderer = $media->renderer();
        if (in_array($mediaType, $whitelist) || (strpos($mediaRenderer, 'youtube') !== false)) {
            $lightMedia[] = $media;
        } else {
            $otherMedia[] = $media;
        }
    }

    //insert universal viewer
    $useUniversalViewer = true;
    foreach ($item->media() as $media) {
        $mediaType = $media->mediaType();
        $mediaRenderer = $media->renderer();
        if (strpos($mediaType, 'image/') === false
            && $mediaType !== 'application/pdf'
            && $mediaRenderer !== 'iiif'
        ) {
            $useUniversalViewer = false;
            break;
        }
    }
    ?>

    <?php echo $this->pageTitle($item->displayTitle(), 2); ?>

    <div class="properties">
        <?php $this->trigger('view.show.after'); ?>
        <div class="allMetadata">
            <?php echo $item->displayValues(); ?>

            <?php if (count($otherMedia) > 0): ?>
                <div id="other-media" class="property">
                    <h4><?php echo $this->translate('Other Media'); ?></h4>
                    <div class="values">
                        <?php foreach ($otherMedia as $media): ?>
                            <div class="value">
                                <a href="<?php echo $media->siteUrl(); ?>"><?php echo $media->displayTitle(); ?></a>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>

            <?php $itemSets = $item->itemSets(); ?>

            <?php if (count($itemSets) > 0): ?>
                <div class="property">
                    <h4><?php echo $this->translate('Item sets'); ?></h4>
                    <div class="values">
                        <?php foreach ($item->itemSets() as $itemSet): ?>
                            <div class="value"><a
                                        href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>

        <?php
        $page = $this->params()->fromQuery('page', 1);
        $property = $this->params()->fromQuery('property');
        $subjectValues = $item->displaySubjectValues($page, 25, $property);
        ?>
        <?php if ($subjectValues): ?>
            <div id="item-linked">
                <h3><?php echo $this->translate('Linked resources'); ?></h3>
                <?php echo $subjectValues; ?>
            </div>
        <?php endif; ?>

    </div>


<?php endif; ?>