<?php // Add class to the <head> for styling. ?>
<?php $this->htmlElement('body')->appendAttribute('class', 'item resource show'); ?>

<?php if ($this->themeSetting('use_show_selector')): ?>

    <?php // If the local BC customizations are turned on in the theme settings, use them. ?>
    <?= $this->DHSelectShowPage($item) ?>

<?php else: ?>

    <?php // Otherwise, show the normal show page ?>
    <?= $this->partial('omeka/site/item/show-original'); ?>

<?php endif; ?>