<?php

/**
 * Show a book
 *
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $item
 */

// Add a class name to the body so we can style based on page.
$this->htmlElement('body')->appendAttribute('class', 'item resource show');

?>

<div class="properties item-show">

    <div class="item-show__main-box-and-media">

        <!-- The IIIF viewer goes in here. It will be rendered where the 'view.show.after' -->
        <!-- trigger fires. -->
        <div class="item-show__media-box">
            <?php $this->trigger('view.show.after'); ?>
            <div class="item-show__rights"><?= $item->value('dcterms:rights') ?></div>
        </div>

        <!-- Title and description -->
        <div class="item-show__metadata-box">
            <h2 class="item-show__title">
                <?= $item->title() ?>
                <span class="item-show__date"><?= $item->value('dcterms:date') ?></span>
            </h2>

            <div class="item-show__description">
                <?= $item->displayDescription() ?>
            </div>

        </div>
    </div>

    <!-- Display a block of metadata -->
    <!-- The items will appear in a grid. Missing fields will not display at all. -->
    <h3 class="item-show__artwork-details-label">Artwork details</h3>
    <div class="item-show__metadata-section item-show__artwork-details">
        <?= $this->DHSingleMetadataField('dcterms:title', $item) ?>
        <?= $this->DHSingleMetadataField('dcterms:subject', $item) ?>
        <?= $this->DHSingleMetadataField('dcterms:title', $item) ?>
        <?= $this->DHSingleMetadataField('dcterms:title', $item) ?>
        <?= $this->DHSingleMetadataField('dcterms:title', $item) ?>
        <?= $this->DHSingleMetadataField('dcterms:title', $item) ?>
    </div>

    <h3 class="item-show__repository-and-provenance-label">Repository and Provenance</h3>
    <div class="item-show__metadata-section item-show__repository-and-provenance">
        <?= $this->DHSingleMetadataField('dcterms:title', $item) ?>
        <?= $this->DHSingleMetadataField('dcterms:title', $item) ?>
        <?= $this->DHSingleMetadataField('dcterms:title', $item) ?>
        <?= $this->DHSingleMetadataField('dcterms:title', $item) ?>
        <?= $this->DHSingleMetadataField('dcterms:provenance', $item) ?>
        <?= $this->DHSingleMetadataField('dcterms:title', $item) ?>
        <?= $this->DHSingleMetadataField('dcterms:title', $item) ?>
        <?= $this->DHSingleMetadataField('dcterms:title', $item) ?>
    </div>

</div>